#!/usr/bin/env node

/**
 * Inject version information into the build
 * This script generates a version file that can be imported at runtime
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read package.json to get version
const packagePath = path.join(__dirname, '..', 'package.json');
const packageData = JSON.parse(fs.readFileSync(packagePath, 'utf8'));

// Create version info object
const versionInfo = {
  version: packageData.version,
  name: packageData.name,
  buildTime: new Date().toISOString(),
  nodeVersion: process.version
};

// Generate version file content
const versionFileContent = `/**
 * Auto-generated version information
 * DO NOT EDIT - This file is automatically generated during build
 */

export const VERSION_INFO = ${JSON.stringify(versionInfo, null, 2)};

export const VERSION = '${packageData.version}';
export const PACKAGE_NAME = '${packageData.name}';
export const BUILD_TIME = '${versionInfo.buildTime}';
`;

// Ensure dist/src directory exists
const distSrcPath = path.join(__dirname, '..', 'dist', 'src');
if (!fs.existsSync(distSrcPath)) {
  fs.mkdirSync(distSrcPath, { recursive: true });
}

// Write version file
const versionFilePath = path.join(distSrcPath, 'version.js');
fs.writeFileSync(versionFilePath, versionFileContent);

// Also create a TypeScript declaration file
const versionDtsContent = `/**
 * Auto-generated version information type definitions
 */

export interface VersionInfo {
  version: string;
  name: string;
  buildTime: string;
  nodeVersion: string;
}

export declare const VERSION_INFO: VersionInfo;
export declare const VERSION: string;
export declare const PACKAGE_NAME: string;
export declare const BUILD_TIME: string;
`;

const versionDtsPath = path.join(distSrcPath, 'version.d.ts');
fs.writeFileSync(versionDtsPath, versionDtsContent);

console.log(`✅ Version ${packageData.version} injected into build`);
console.log(`   - Version file: ${versionFilePath}`);
console.log(`   - Build time: ${versionInfo.buildTime}`);