# Beta Deployment Workflow
# Deploys beta versions to npm when pushing to develop branch

name: Beta Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        continue-on-error: true
        
      - name: Build
        run: npm run build
        
      - name: Update version for beta
        run: |
          # Get current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          # Remove any existing pre-release suffix
          BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-.*$//')
          # Add beta suffix with timestamp
          BETA_VERSION="${BASE_VERSION}-beta.$(date +%Y%m%d%H%M%S)"
          
          # Update package.json
          npm version $BETA_VERSION --no-git-tag-version --allow-same-version
          echo "BETA_VERSION=$BETA_VERSION" >> $GITHUB_ENV
          
      - name: Publish to NPM
        run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Summary
        run: |
          echo "## 🚀 Beta Deployment Successful!" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ env.BETA_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "**Install:** \`npm install @digitalsamba/embedded-api-mcp-server@beta\`" >> $GITHUB_STEP_SUMMARY