name: Coverage Badge

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-coverage-badge:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage
      run: npm run test:coverage

    - name: Generate coverage badge
      uses: jpb06/jest-coverage-badges-action@latest
      with:
        coverage-summary-path: ./coverage/coverage-summary.json
        branches: main
        
    - name: Update README with dynamic badge
      run: |
        COVERAGE=$(node -p "Math.round(require('./coverage/coverage-summary.json').total.lines.pct)")
        
        # Update the badge in README
        sed -i "s/coverage-[0-9]*%25/coverage-${COVERAGE}%25/g" README.md
        
        # Update color based on coverage
        if [ $COVERAGE -ge 80 ]; then
          sed -i "s/coverage-${COVERAGE}%25-[a-z]*/coverage-${COVERAGE}%25-brightgreen/g" README.md
        elif [ $COVERAGE -ge 60 ]; then
          sed -i "s/coverage-${COVERAGE}%25-[a-z]*/coverage-${COVERAGE}%25-yellow/g" README.md
        else
          sed -i "s/coverage-${COVERAGE}%25-[a-z]*/coverage-${COVERAGE}%25-red/g" README.md
        fi

    - name: Commit badge update
      uses: EndBug/add-and-commit@v9
      with:
        add: 'README.md'
        message: 'chore: update coverage badge [skip ci]'
        default_author: github_actions