name: PR Tests

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/pr-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    name: Test on Node ${{ matrix.node-version }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
      continue-on-error: true  # Don't fail the whole job on lint errors
    
    - name: Security audit
      run: npm audit --production --audit-level=high
    
    - name: Run tests
      run: npm test
      env:
        DIGITAL_SAMBA_API_KEY: ${{ secrets.TEST_API_KEY }}
        NODE_ENV: test
    
    - name: Build check
      run: npm run build
    
    - name: Check package size
      run: npm run size-check
    
    - name: Test package packing
      run: |
        npm pack --dry-run
        echo "✅ Package can be successfully packed"

  # Add status check that all tests passed
  tests-passed:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: All tests passed
      if: ${{ needs.test.result == 'success' }}
      run: echo "✅ All tests passed successfully!"
      
    - name: Tests failed
      if: ${{ needs.test.result != 'success' }}
      run: |
        echo "❌ Tests failed!"
        exit 1