name: Test NPM Authentication

on:
  workflow_dispatch:

jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          
      - name: Test NPM Authentication
        run: |
          echo "Testing npm authentication..."
          echo "NODE_AUTH_TOKEN exists: ${{ secrets.NPM_TOKEN != '' }}"
          
          # Check npm config
          echo "NPM Config:"
          npm config list
          
          # Try whoami
          echo "Testing npm whoami:"
          npm whoami || echo "npm whoami failed"
          
          # Check package info
          echo "Package name: $(node -p "require('./package.json').name")"
          echo "Package version: $(node -p "require('./package.json').version")"
          
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}